// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

package wickr

import (
	"context"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/wickr"
	awstypes "github.com/aws/aws-sdk-go-v2/service/wickr/types"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-aws/internal/errs"
	"github.com/hashicorp/terraform-provider-aws/internal/errs/fwdiag"
	"github.com/hashicorp/terraform-provider-aws/internal/framework"
	fwflex "github.com/hashicorp/terraform-provider-aws/internal/framework/flex"
	"github.com/hashicorp/terraform-provider-aws/internal/retry"
	"github.com/hashicorp/terraform-provider-aws/internal/smerr"
	"github.com/hashicorp/terraform-provider-aws/names"
)

// Design choice: SNS email subscription pattern for enabled/pubkey_msg_acked.
//
// The Wickr data retention bot has a two-phase setup that mirrors
// aws_sns_topic_subscription with protocol="email":
//
//  1. Terraform creates the bot and generates the challenge password.
//  2. The user configures their external data-retention daemon with the
//     challenge password (out-of-band, like clicking an SNS confirmation link).
//  3. The daemon connects and registers with the bot.
//  4. Only after registration does the UpdateDataRetention API accept
//     ENABLE/DISABLE/PUBKEY_MSG_ACK actions.
//
// Because step 3 is an out-of-band process that Terraform cannot drive,
// the `enabled` and `pubkey_msg_acked` attributes are Computed-only —
// they reflect the current state reported by GetDataRetentionBot, just
// like `confirmation_was_authenticated` on an SNS email subscription.
// Users manage the enable/disable toggle via the AWS CLI or console
// after their daemon has registered. `terraform refresh` picks up the
// updated state.
//
// The `challenge` attribute follows the aws_iam_access_key.secret pattern:
// a one-time-generated credential stored as Computed+Sensitive in state.

// @FrameworkResource("aws_wickr_data_retention_bot", name="Data Retention Bot")
// @IdentityAttribute("network_id")
// @Testing(existsType="github.com/aws/aws-sdk-go-v2/service/wickr;wickr.GetDataRetentionBotOutput")
// @Testing(preCheck="testAccPreCheck")
// @Testing(serialize=true)
// @Testing(tagsTest=false)
// @Testing(hasNoPreExistingResource=true)
func newDataRetentionBotResource(_ context.Context) (resource.ResourceWithConfigure, error) {
	r := &dataRetentionBotResource{}

	r.SetDefaultCreateTimeout(30 * time.Minute)
	r.SetDefaultReadTimeout(10 * time.Minute)
	r.SetDefaultUpdateTimeout(30 * time.Minute)
	r.SetDefaultDeleteTimeout(30 * time.Minute)

	return r, nil
}

const (
	ResNameDataRetentionBot = "Data Retention Bot"
)

type dataRetentionBotResource struct {
	framework.ResourceWithModel[dataRetentionBotResourceModel]
	framework.WithTimeouts
	framework.WithImportByIdentity
}

func (r *dataRetentionBotResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"network_id": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			// challenge is the daemon-side password generated by
			// CreateDataRetentionBotChallenge during Create. It is consumed
			// by the customer-operated data-retention daemon process to
			// authenticate against the bot. The API does not return this
			// value on subsequent reads (GetDataRetentionBot only has
			// BotExists), so it persists in state from Create only.
			//
			// This follows the aws_iam_access_key.secret pattern: a
			// one-time-generated credential stored as Computed+Sensitive.
			// State is encrypted at rest in all Terraform backends.
			"challenge": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			// enabled maps to IsDataRetentionServiceEnabled in the API.
			// Toggled via UpdateDataRetention with ActionType ENABLE/DISABLE.
			// Computed-only because the toggle requires the external
			// data-retention daemon to have completed registration (connected
			// using the challenge password). Without daemon registration,
			// UpdateDataRetention returns "Data retention bot not found or
			// not registered". The enabled state reflects what the daemon
			// has configured, not what Terraform can control directly.
			names.AttrEnabled: schema.BoolAttribute{
				Computed: true,
			},
			// pubkey_msg_acked maps to IsPubkeyMsgAcked in the API.
			// Computed-only for the same reason as enabled — requires
			// daemon registration before the PUBKEY_MSG_ACK action works.
			"pubkey_msg_acked": schema.BoolAttribute{
				Computed: true,
			},
			"bot_exists": schema.BoolAttribute{
				Computed: true,
			},
			"bot_name": schema.StringAttribute{
				Computed: true,
			},
			"is_bot_active": schema.BoolAttribute{
				Computed: true,
			},
			"is_data_retention_bot_registered": schema.BoolAttribute{
				Computed: true,
			},
		},
		Blocks: map[string]schema.Block{
			names.AttrTimeouts: timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

func (r *dataRetentionBotResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dataRetentionBotResourceModel
	smerr.AddEnrich(ctx, &resp.Diagnostics, req.Plan.Get(ctx, &plan))
	if resp.Diagnostics.HasError() {
		return
	}

	conn := r.Meta().WickrClient(ctx)
	networkID := plan.NetworkID.ValueString()

	// Step 1: Create the data retention bot.
	createInput := wickr.CreateDataRetentionBotInput{
		NetworkId: aws.String(networkID),
	}
	_, err := conn.CreateDataRetentionBot(ctx, &createInput)
	if err != nil {
		smerr.AddError(ctx, &resp.Diagnostics, err, smerr.ID, networkID)
		return
	}

	// Step 2: Generate the challenge password. This registers the bot
	// with the data-retention service, which is a prerequisite for the
	// external daemon to connect. The password is consumed by the
	// customer-operated data-retention daemon and is stored in Terraform
	// state (Computed+Sensitive), following the aws_iam_access_key.secret
	// pattern.
	challengeInput := wickr.CreateDataRetentionBotChallengeInput{
		NetworkId: aws.String(networkID),
	}
	challengeOut, err := conn.CreateDataRetentionBotChallenge(ctx, &challengeInput)
	if err != nil {
		smerr.AddError(ctx, &resp.Diagnostics, err, smerr.ID, networkID)
		return
	}
	plan.Challenge = fwflex.StringToFramework(ctx, challengeOut.Challenge)

	// Step 3: Re-read to populate all Computed fields.
	out, err := findDataRetentionBotByID(ctx, conn, networkID)
	if err != nil {
		smerr.AddError(ctx, &resp.Diagnostics, err, smerr.ID, networkID)
		return
	}

	// Preserve the challenge from step 2 — GetDataRetentionBot does not
	// return the password.
	challenge := plan.Challenge

	flattenDataRetentionBot(ctx, out, &plan)

	plan.Challenge = challenge

	smerr.AddEnrich(ctx, &resp.Diagnostics, resp.State.Set(ctx, &plan))
}

func (r *dataRetentionBotResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dataRetentionBotResourceModel
	smerr.AddEnrich(ctx, &resp.Diagnostics, req.State.Get(ctx, &state))
	if resp.Diagnostics.HasError() {
		return
	}

	conn := r.Meta().WickrClient(ctx)
	networkID := state.NetworkID.ValueString()

	out, err := findDataRetentionBotByID(ctx, conn, networkID)
	if retry.NotFound(err) {
		resp.Diagnostics.Append(fwdiag.NewResourceNotFoundWarningDiagnostic(err))
		resp.State.RemoveResource(ctx)
		return
	}
	// Mirror the Network/SecurityGroup/Bot pattern: treat ForbiddenError
	// and orphaned-child deserialization failures as "gone" so terraform
	// refresh after an out-of-band parent-network delete cleanly removes
	// the resource from state.
	if isDataRetentionBotOrphanedChildError(err) {
		resp.Diagnostics.Append(fwdiag.NewResourceNotFoundWarningDiagnostic(err))
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		smerr.AddError(ctx, &resp.Diagnostics, err, smerr.ID, networkID)
		return
	}

	// Preserve the challenge from prior state — GetDataRetentionBot does
	// not return the password. On import, prior state is empty, so
	// challenge will be null — that's correct because the password was
	// only available at creation time.
	challenge := state.Challenge

	flattenDataRetentionBot(ctx, out, &state)

	state.Challenge = challenge

	smerr.AddEnrich(ctx, &resp.Diagnostics, resp.State.Set(ctx, &state))
}

func (r *dataRetentionBotResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No user-settable fields can be updated. enabled and pubkey_msg_acked
	// are Computed-only (they require the external daemon to register
	// before UpdateDataRetention works), and network_id is RequiresReplace.
	// This handler exists only to satisfy the framework interface; it
	// re-reads the current state from AWS.
	var plan dataRetentionBotResourceModel
	smerr.AddEnrich(ctx, &resp.Diagnostics, req.Plan.Get(ctx, &plan))
	if resp.Diagnostics.HasError() {
		return
	}

	var state dataRetentionBotResourceModel
	smerr.AddEnrich(ctx, &resp.Diagnostics, req.State.Get(ctx, &state))
	if resp.Diagnostics.HasError() {
		return
	}

	conn := r.Meta().WickrClient(ctx)
	networkID := state.NetworkID.ValueString()

	out, err := findDataRetentionBotByID(ctx, conn, networkID)
	if err != nil {
		smerr.AddError(ctx, &resp.Diagnostics, err, smerr.ID, networkID)
		return
	}

	// Preserve the challenge from prior state.
	challenge := state.Challenge

	flattenDataRetentionBot(ctx, out, &plan)

	plan.Challenge = challenge

	smerr.AddEnrich(ctx, &resp.Diagnostics, resp.State.Set(ctx, &plan))
}

func (r *dataRetentionBotResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dataRetentionBotResourceModel
	smerr.AddEnrich(ctx, &resp.Diagnostics, req.State.Get(ctx, &state))
	if resp.Diagnostics.HasError() {
		return
	}

	conn := r.Meta().WickrClient(ctx)
	networkID := state.NetworkID.ValueString()

	input := wickr.DeleteDataRetentionBotInput{
		NetworkId: aws.String(networkID),
	}
	_, err := conn.DeleteDataRetentionBot(ctx, &input)
	// Treat already-gone responses as success: ResourceNotFoundError,
	// ForbiddenError (parent network deleting), orphaned-child
	// deserialization failures.
	if errs.IsA[*awstypes.ResourceNotFoundError](err) || isDataRetentionBotOrphanedChildError(err) {
		return
	}
	if err != nil {
		smerr.AddError(ctx, &resp.Diagnostics, err, smerr.ID, networkID)
		return
	}
}

func (r *dataRetentionBotResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("network_id"), req, resp)
}

// isDataRetentionBotOrphanedChildError returns true when err indicates the
// data retention bot (or its parent network) is gone. Mirrors
// isBotOrphanedChildError.
func isDataRetentionBotOrphanedChildError(err error) bool {
	if err == nil {
		return false
	}
	if errs.IsA[*awstypes.ForbiddenError](err) {
		return true
	}
	msg := err.Error()
	return strings.Contains(msg, "StatusCode: 401") ||
		strings.Contains(msg, "deserialization failed")
}

// flattenDataRetentionBot populates the model from a GetDataRetentionBotOutput.
// AutoFlex cannot be used here because the SDK output field names
// (BotExists, BotName, IsBotActive, IsDataRetentionBotRegistered,
// IsDataRetentionServiceEnabled, IsPubkeyMsgAcked) do not match the
// Terraform schema attribute names (bot_exists, bot_name, is_bot_active,
// is_data_retention_bot_registered, enabled, pubkey_msg_acked). The last
// two are intentional renames for user-friendliness.
// nosemgrep:ci.semgrep.framework.manual-flattener-functions
func flattenDataRetentionBot(ctx context.Context, out *wickr.GetDataRetentionBotOutput, m *dataRetentionBotResourceModel) {
	if out == nil {
		return
	}

	m.BotExists = fwflex.BoolToFramework(ctx, out.BotExists)
	m.BotName = fwflex.StringToFramework(ctx, out.BotName)
	m.IsBotActive = fwflex.BoolToFramework(ctx, out.IsBotActive)
	m.IsDataRetentionBotRegistered = fwflex.BoolToFramework(ctx, out.IsDataRetentionBotRegistered)
	m.Enabled = fwflex.BoolToFramework(ctx, out.IsDataRetentionServiceEnabled)
	m.PubkeyMsgAcked = fwflex.BoolToFramework(ctx, out.IsPubkeyMsgAcked)
}

// dataRetentionBotResourceModel mirrors the Framework-resource schema.
type dataRetentionBotResourceModel struct {
	framework.WithRegionModel
	NetworkID                    types.String   `tfsdk:"network_id"`
	Challenge                    types.String   `tfsdk:"challenge"`
	Enabled                      types.Bool     `tfsdk:"enabled"`
	PubkeyMsgAcked               types.Bool     `tfsdk:"pubkey_msg_acked"`
	BotExists                    types.Bool     `tfsdk:"bot_exists"`
	BotName                      types.String   `tfsdk:"bot_name"`
	IsBotActive                  types.Bool     `tfsdk:"is_bot_active"`
	IsDataRetentionBotRegistered types.Bool     `tfsdk:"is_data_retention_bot_registered"`
	Timeouts                     timeouts.Value `tfsdk:"timeouts"`
}
