// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/generate/servicepackage/main.go; DO NOT EDIT.

package wickr

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/wickr"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	inttypes "github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/internal/vcr"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*inttypes.ServicePackageFrameworkDataSource {
	return []*inttypes.ServicePackageFrameworkDataSource{
		{
			Factory:  newBotDataSource,
			TypeName: "aws_wickr_bot",
			Name:     "Bot",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newBotsDataSource,
			TypeName: "aws_wickr_bots",
			Name:     "Bots",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newNetworkDataSource,
			TypeName: "aws_wickr_network",
			Name:     "Network",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newNetworkSettingsDataSource,
			TypeName: "aws_wickr_network_settings",
			Name:     "Network Settings",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newNetworksDataSource,
			TypeName: "aws_wickr_networks",
			Name:     "Networks",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newOIDCConfigDataSource,
			TypeName: "aws_wickr_oidc_config",
			Name:     "OIDC Config",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newSecurityGroupDataSource,
			TypeName: "aws_wickr_security_group",
			Name:     "Security Group",
			Region:   inttypes.ResourceRegionDefault(),
		},
		{
			Factory:  newSecurityGroupsDataSource,
			TypeName: "aws_wickr_security_groups",
			Name:     "Security Groups",
			Region:   inttypes.ResourceRegionDefault(),
		},
	}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*inttypes.ServicePackageFrameworkResource {
	return []*inttypes.ServicePackageFrameworkResource{
		{
			Factory:  newBotResource,
			TypeName: "aws_wickr_bot",
			Name:     "Bot",
			Region:   inttypes.ResourceRegionDefault(),
			Identity: inttypes.RegionalParameterizedIdentity([]inttypes.IdentityAttribute{
				inttypes.StringIdentityAttribute("network_id", true),
				inttypes.StringIdentityAttribute("bot_id", true),
			}),
			Import: inttypes.FrameworkImport{
				WrappedImport: true,
				ImportID:      botImportID{},
			},
		},
		{
			Factory:  newDataRetentionBotResource,
			TypeName: "aws_wickr_data_retention_bot",
			Name:     "Data Retention Bot",
			Region:   inttypes.ResourceRegionDefault(),
			Identity: inttypes.RegionalSingleParameterIdentity("network_id"),
			Import: inttypes.FrameworkImport{
				WrappedImport: true,
			},
		},
		{
			Factory:  newNetworkResource,
			TypeName: "aws_wickr_network",
			Name:     "Network",
			Region:   inttypes.ResourceRegionDefault(),
			Identity: inttypes.RegionalARNIdentity(),
			Import: inttypes.FrameworkImport{
				WrappedImport: true,
			},
		},
		{
			Factory:  newNetworkSettingsResource,
			TypeName: "aws_wickr_network_settings",
			Name:     "Network Settings",
			Region:   inttypes.ResourceRegionDefault(),
			Identity: inttypes.RegionalSingleParameterIdentity("network_id"),
			Import: inttypes.FrameworkImport{
				WrappedImport: true,
			},
		},
		{
			Factory:  newOIDCConfigResource,
			TypeName: "aws_wickr_oidc_config",
			Name:     "OIDC Config",
			Region:   inttypes.ResourceRegionDefault(),
			Identity: inttypes.RegionalSingleParameterIdentity("network_id"),
			Import: inttypes.FrameworkImport{
				WrappedImport: true,
			},
		},
		{
			Factory:  newSecurityGroupResource,
			TypeName: "aws_wickr_security_group",
			Name:     "Security Group",
			Region:   inttypes.ResourceRegionDefault(),
			Identity: inttypes.RegionalParameterizedIdentity([]inttypes.IdentityAttribute{
				inttypes.StringIdentityAttribute("network_id", true),
				inttypes.StringIdentityAttribute("security_group_id", true),
			}),
			Import: inttypes.FrameworkImport{
				WrappedImport: true,
				ImportID:      securityGroupImportID{},
			},
		},
	}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*inttypes.ServicePackageSDKDataSource {
	return []*inttypes.ServicePackageSDKDataSource{}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*inttypes.ServicePackageSDKResource {
	return []*inttypes.ServicePackageSDKResource{}
}

func (p *servicePackage) ServicePackageName() string {
	return names.Wickr
}

// NewClient returns a new AWS SDK for Go v2 client for this service package's AWS API.
func (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*wickr.Client, error) {
	cfg := *(config["aws_sdkv2_config"].(*aws.Config))
	optFns := []func(*wickr.Options){
		wickr.WithEndpointResolverV2(newEndpointResolverV2()),
		withBaseEndpoint(config[names.AttrEndpoint].(string)),
		func(o *wickr.Options) {
			if region := config[names.AttrRegion].(string); o.Region != region {
				tflog.Info(ctx, "overriding provider-configured AWS API region", map[string]any{
					"service":         p.ServicePackageName(),
					"original_region": o.Region,
					"override_region": region,
				})
				o.Region = region
			}
		},
		func(o *wickr.Options) {
			if inContext, ok := conns.FromContext(ctx); ok && inContext.VCREnabled() {
				tflog.Info(ctx, "overriding retry behavior to immediately return VCR errors")
				o.Retryer = conns.AddIsErrorRetryables(cfg.Retryer().(aws.RetryerV2), vcr.InteractionNotFoundRetryableFunc)
			}
		},
		withExtraOptions(ctx, p, config),
	}

	return wickr.NewFromConfig(cfg, optFns...), nil
}

// withExtraOptions returns a functional option that allows this service package to specify extra API client options.
// This option is always called after any generated options.
func withExtraOptions(ctx context.Context, sp conns.ServicePackage, config map[string]any) func(*wickr.Options) {
	if v, ok := sp.(interface {
		withExtraOptions(context.Context, map[string]any) []func(*wickr.Options)
	}); ok {
		optFns := v.withExtraOptions(ctx, config)

		return func(o *wickr.Options) {
			for _, optFn := range optFns {
				optFn(o)
			}
		}
	}

	return func(*wickr.Options) {}
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
